package com.mycompany.th1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad T480s
 */
public class Program extends javax.swing.JFrame {

    private ArrayList<Student> students;

    public Program() {
        initComponents();
        setLocationRelativeTo(null);
        students = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjlbNhanVien = new javax.swing.JLabel();
        jtextNgaysinh = new javax.swing.JTextField();
        jtextHoten = new javax.swing.JTextField();
        jtextDiachi = new javax.swing.JTextField();
        jtextDiemtk = new javax.swing.JTextField();
        jtextEmail = new javax.swing.JTextField();
        jtextMasv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jChecknam = new javax.swing.JCheckBox();
        jChecknu = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbThem = new javax.swing.JButton();
        jThoat = new javax.swing.JButton();
        JbLuutru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jjlbNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jjlbNhanVien.setForeground(new java.awt.Color(255, 0, 51));
        jjlbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jjlbNhanVien.setText("THONG TIN SINH VIEN");

        jtextHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextHotenActionPerformed(evt);
            }
        });

        jtextDiemtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextDiemtkActionPerformed(evt);
            }
        });

        jtextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextEmailActionPerformed(evt);
            }
        });

        jtextMasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextMasvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ho Ten : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ngay Sinh :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dia Chi :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ma SV  :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Gioi Tinh :");

        jChecknam.setText("Nam");

        jChecknu.setText("Nu");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email  : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Diem TKet :");

        jbThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbThem.setText("Them SV");
        jbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemActionPerformed(evt);
            }
        });

        jThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jThoat.setText("Thoat");
        jThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThoatActionPerformed(evt);
            }
        });

        JbLuutru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JbLuutru.setText("Luu Tru");
        JbLuutru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbLuutruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextNgaysinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextHoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(776, 776, 776))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjlbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jChecknam)
                                .addGap(18, 18, 18)
                                .addComponent(jChecknu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtextDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtextDiemtk, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtextEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtextMasv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(200, 200, 200))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbThem)
                                .addGap(109, 109, 109)
                                .addComponent(JbLuutru)
                                .addGap(99, 99, 99)
                                .addComponent(jThoat)
                                .addGap(54, 54, 54))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jjlbNhanVien)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(87, 87, 87)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextDiemtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jChecknam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChecknu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jThoat)
                            .addComponent(jbThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbLuutru, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextMasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextMasvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextMasvActionPerformed

    private void jtextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextEmailActionPerformed

    private void jThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jThoatActionPerformed

    private void jtextHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextHotenActionPerformed

    }//GEN-LAST:event_jtextHotenActionPerformed

    private void jbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemActionPerformed
        // TODO add your handling code here:
        Student sv = new Student();
        if (!jtextHoten.getText().isEmpty()) {
            sv.setHoTen(jtextHoten.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }
        if (!jtextNgaysinh.getText().isEmpty()) {
            sv.setNgaySinh(jtextNgaysinh.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }
        if (!jtextDiachi.getText().isEmpty()) {
            sv.setDiaChi(jtextDiachi.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }

        if (jChecknam.isSelected() && jChecknu.isSelected()) {
            JOptionPane.showMessageDialog(null, "Chi chon mot gioi tinh!");
            return;
        }

        if (jChecknam.isSelected()) {
            sv.setGioiTinh("Nam");
        } else if (jChecknu.isSelected()) {
            sv.setGioiTinh("Nu");
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le");
            return;
        }
        if (!jtextMasv.getText().isEmpty()) {
            sv.setMaSV(jtextMasv.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }
        if (!jtextEmail.getText().isEmpty()) {
            sv.setEmail(jtextEmail.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }
        try {
            double b = Double.parseDouble(jtextDiemtk.getText());
            if (b <= 10 && b >= 0) {
                sv.setDiemTK(b);
            } else {
                JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Du lieu nhap khong hop le!");
            return;
        }
        sv.hienThiThongTin();
        students.add(sv);
        JOptionPane.showMessageDialog(rootPane, "Them sinh vien thanh cong!");
    }//GEN-LAST:event_jbThemActionPerformed

    private void jtextDiemtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextDiemtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextDiemtkActionPerformed

    @SuppressWarnings("empty-statement")
    private void JbLuutruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbLuutruActionPerformed
        // TODO add your handling code here:

        try {
            File file = new File("sinhvien.dat");
            PrintWriter pf = new PrintWriter(file);
            for (Student x : students) {
                pf.printf("%-25s %-25s %-25s %-25s %-25s %-25s %-25.2f\n",
                        x.getHoTen(),
                        x.getNgaySinh(),
                        x.getDiaChi(),
                        x.getGioiTinh(),
                        x.getMaSV(),
                        x.getEmail(),
                        x.getDiemTK());

            }
            pf.close();
            JOptionPane.showMessageDialog(rootPane, "Ghi file thanh cong!");
        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_JbLuutruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbLuutru;
    private javax.swing.JCheckBox jChecknam;
    private javax.swing.JCheckBox jChecknu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jThoat;
    private javax.swing.JButton jbThem;
    private javax.swing.JLabel jjlbNhanVien;
    private javax.swing.JTextField jtextDiachi;
    private javax.swing.JTextField jtextDiemtk;
    private javax.swing.JTextField jtextEmail;
    private javax.swing.JTextField jtextHoten;
    private javax.swing.JTextField jtextMasv;
    private javax.swing.JTextField jtextNgaysinh;
    // End of variables declaration//GEN-END:variables
}
