package com.mycompany.de3;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad T480s
 */
public class TabSinhVien extends javax.swing.JFrame {

    private ArrayList<SinhVienATTT> dsATTTs;
    private ArrayList<SinhVienMatMa> dsMatMas;

    /**
     * Creates new form FrameProgram
     */
    public TabSinhVien() {
        initComponents();
        setLocationRelativeTo(null);
        dsATTTs = new ArrayList<>();
        dsMatMas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        MASV1 = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        GIOITINH1 = new javax.swing.JTextField();
        b = new javax.swing.JLabel();
        HOTEN1 = new javax.swing.JTextField();
        e = new javax.swing.JLabel();
        DIEMTB1 = new javax.swing.JTextField();
        c = new javax.swing.JLabel();
        NGAYSINH1 = new javax.swing.JTextField();
        f = new javax.swing.JLabel();
        HOCPHI1 = new javax.swing.JTextField();
        GHIVAOFILE1 = new javax.swing.JButton();
        JTHOAT2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMASV1 = new javax.swing.JLabel();
        jdaubuoi = new javax.swing.JLabel();
        JNGAYSINH1 = new javax.swing.JLabel();
        JGIOITINH1 = new javax.swing.JLabel();
        JTRUNGBINH1 = new javax.swing.JLabel();
        JTROCAP = new javax.swing.JLabel();
        MASV2 = new javax.swing.JTextField();
        HOTEN2 = new javax.swing.JTextField();
        NGAYSINH2 = new javax.swing.JTextField();
        GIOITINH2 = new javax.swing.JTextField();
        DIEMTB2 = new javax.swing.JTextField();
        TROPCAP2 = new javax.swing.JTextField();
        GHIVAOFILE2 = new javax.swing.JButton();
        JTHOAT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SINH VIEN AN TOAN THONG TIN");

        a.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        a.setText("MA SV");

        d.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d.setText("GIOI TINH");

        b.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b.setText("Ho Ten");

        e.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        e.setText("DIEM TB");

        c.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        c.setText("Ngay Sinh");

        f.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f.setText("HOC PHI");

        GHIVAOFILE1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GHIVAOFILE1.setForeground(new java.awt.Color(0, 255, 255));
        GHIVAOFILE1.setText("GHI VAO FILE");
        GHIVAOFILE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GHIVAOFILE1ActionPerformed(evt);
            }
        });

        JTHOAT2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTHOAT2.setForeground(new java.awt.Color(0, 255, 255));
        JTHOAT2.setText("Thoat");
        JTHOAT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTHOAT2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NGAYSINH1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(HOTEN1)
                            .addComponent(MASV1)))
                    .addComponent(GHIVAOFILE1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(e)
                                    .addGap(60, 60, 60))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(d)
                                    .addGap(37, 37, 37)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GIOITINH1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DIEMTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(f)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HOCPHI1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JTHOAT2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d)
                            .addComponent(a)
                            .addComponent(MASV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GIOITINH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b)
                    .addComponent(e)
                    .addComponent(HOTEN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DIEMTB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f)
                            .addComponent(HOCPHI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NGAYSINH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GHIVAOFILE1)
                    .addComponent(JTHOAT2))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("SinhVienAnToan", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SINH VIEN MA MA");

        jMASV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMASV1.setText("MA SV");

        jdaubuoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jdaubuoi.setText("Ho Ten");

        JNGAYSINH1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JNGAYSINH1.setText("Ngay Sinh");

        JGIOITINH1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JGIOITINH1.setText("GIOI TINH");

        JTRUNGBINH1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTRUNGBINH1.setText("DIEM TB");

        JTROCAP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTROCAP.setText("TRO CAP");

        GHIVAOFILE2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GHIVAOFILE2.setForeground(new java.awt.Color(0, 255, 255));
        GHIVAOFILE2.setText("GHI VAO FILE");
        GHIVAOFILE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GHIVAOFILE2ActionPerformed(evt);
            }
        });

        JTHOAT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTHOAT1.setForeground(new java.awt.Color(0, 255, 255));
        JTHOAT1.setText("Thoat");
        JTHOAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTHOAT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdaubuoi)
                            .addComponent(jMASV1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JNGAYSINH1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NGAYSINH2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(HOTEN2)
                            .addComponent(MASV2)))
                    .addComponent(GHIVAOFILE2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(JTRUNGBINH1)
                                    .addGap(60, 60, 60))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(JGIOITINH1)
                                    .addGap(37, 37, 37)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GIOITINH2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DIEMTB2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(JTROCAP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TROPCAP2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JTHOAT1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JGIOITINH1)
                            .addComponent(jMASV1)
                            .addComponent(MASV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GIOITINH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdaubuoi)
                    .addComponent(JTRUNGBINH1)
                    .addComponent(HOTEN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DIEMTB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTROCAP)
                            .addComponent(TROPCAP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NGAYSINH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JNGAYSINH1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GHIVAOFILE2)
                    .addComponent(JTHOAT1))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("SinhVienMatMa", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTHOAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTHOAT1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JTHOAT1ActionPerformed

    private void JTHOAT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTHOAT2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JTHOAT2ActionPerformed

    private void GHIVAOFILE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GHIVAOFILE1ActionPerformed
        // TODO add your handling code here:
        SinhVienATTT svatt = new SinhVienATTT();
        svatt.setMaSV(MASV1.getText());
        svatt.setHoTen(HOTEN1.getText());
        svatt.setNgaySinh(NGAYSINH1.getText());
        svatt.setGioiTinh(GIOITINH1.getText());
        svatt.setDiemTB(Double.parseDouble(DIEMTB1.getText()));
        svatt.setHocPhi(Double.parseDouble(HOCPHI1.getText()));
        dsATTTs.add(svatt);
        try {
            File file = new File("svatt.dat");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            for (SinhVienATTT sv : dsATTTs) {
                bw.write(sv.hienThiThongTin());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(rootPane, "Ghi file sinh vien an toan thanh cong thanh cong");
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_GHIVAOFILE1ActionPerformed

    private void GHIVAOFILE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GHIVAOFILE2ActionPerformed
            // TODO add your handling code here:
             SinhVienMatMa svmm = new SinhVienMatMa();
        svmm.setMaSV(MASV2.getText());
        svmm.setHoTen(HOTEN2.getText());
        svmm.setNgaySinh(NGAYSINH2.getText());
        svmm.setGioiTinh(GIOITINH2.getText());
        svmm.setDiemTB(Double.parseDouble(DIEMTB2.getText()));
        svmm.setTroCap(Double.parseDouble(TROPCAP2.getText()));
        dsMatMas.add(svmm);
        try {
            File file = new File("svmatma.dat");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            for (SinhVienMatMa sv : dsMatMas) {
                bw.write(sv.hienThiThongTin());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(rootPane, "Ghi file sinh vien mat ma thanh cong thanh cong");
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_GHIVAOFILE2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DIEMTB1;
    private javax.swing.JTextField DIEMTB2;
    private javax.swing.JButton GHIVAOFILE1;
    private javax.swing.JButton GHIVAOFILE2;
    private javax.swing.JTextField GIOITINH1;
    private javax.swing.JTextField GIOITINH2;
    private javax.swing.JTextField HOCPHI1;
    private javax.swing.JTextField HOTEN1;
    private javax.swing.JTextField HOTEN2;
    private javax.swing.JLabel JGIOITINH1;
    private javax.swing.JLabel JNGAYSINH1;
    private javax.swing.JButton JTHOAT1;
    private javax.swing.JButton JTHOAT2;
    private javax.swing.JLabel JTROCAP;
    private javax.swing.JLabel JTRUNGBINH1;
    private javax.swing.JTextField MASV1;
    private javax.swing.JTextField MASV2;
    private javax.swing.JTextField NGAYSINH1;
    private javax.swing.JTextField NGAYSINH2;
    private javax.swing.JTextField TROPCAP2;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jMASV1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jdaubuoi;
    // End of variables declaration//GEN-END:variables
}
